### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by azharichenko** [Pitt-CSC/PittAPI#34]
This issue will deal with making consistent documentation within the project's code and with the docs. The **plans below are subject to change** and will include more issues/enhancements to deal with as they come up. Each issue will have the pull request or issue that they are resolved in. If there are any other documentation features you would like to be included please comment below.

## Documentation Structure

- [x] Moving from `DOCS.md` to `docs/` ( #35 )
- [x] Spliting `DOCS.md` into seperate API DOCS ( #35 )
- [x] Create template for adding functions to docs

## Doc Improvements

- [ ] Adding usage example to each function in the API ( #35, #43, #48, #55, #56, 6862373)
- [ ] Adding descriptions of parameters and returns of each function ( #35, #43, #48, #55, #56)

## Code Documentation

- [ ] All functions have `docstrings` ( #43, #55, #56 )
- [ ] All `docstrings` comply with [PEP 257](https://www.python.org/dev/peps/pep-0257/) ( #43, #55, #56 )

**Comment by Rahi374** [comment]
https://en.wikipedia.org/wiki/Docstring

I know this is from Wikipedia and not PEP, but it says that the first line of the module can be the docstring, so would that mean that every module that we have has a copyright notice as the docstring?

**Comment by RitwikGupta** [comment]
Yeah, pretty much at the moment, as an artifact from the original layout

**Comment by Rahi374** [comment]
So then are we going to boot out the copyright notice or move that as the second thing in the file?
